name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest          # <— Windows runner

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6 LTS
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./L.A.T.E.csproj

      - name: Build (Release)
        run: dotnet build ./L.A.T.E.csproj -c Release --no-restore